LMS.Web/Controllers/CorporationController.cs
using AutoMapper;
using AutoMapper.QueryableExtensions;

using LMS.IService.IServices;
using LMS.Model;
using LMS.Model.Dto;
using LMS.Model.Entities;
using LMS.Model.Extend;
using LMS.Web.Models;
using LMS.Web.Utility;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

namespace LMS.Web.Controllers
{
    /// <summary>
    /// 企业控制器
    /// </summary>
    public class CorporationController : SharedController
    {

        public CorporationController(IMapper mapper,
                                     IAreaService areaService,
                                     ICorporationService corporationService) : base(mapper, areaService, corporationService)
        {
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult CorporationList()
        {
            return View();
        }
        [HttpPost]
        public ActionResult<PageData<CorporationDto>> CorporationListData([FromBody] CorporationSearchParamsDto paramsDto)
        {
            if (paramsDto is null)
            {
                throw new ArgumentNullException(nameof(paramsDto));
            }
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "");
            }
            Expression<Func<Corporation, bool>> whereLambda = w => true;
            Expression<Func<Corporation, object>> orderLambda = w => true;
            if (!string.IsNullOrWhiteSpace(paramsDto.Name))
            {
                whereLambda.And(s => s.Name.Contains(paramsDto.Name));
            }
            if (string.IsNullOrWhiteSpace(paramsDto.CorporationAddress))
            {
                whereLambda.And(s => s.CorporationAddress.Contains(paramsDto.CorporationAddress));
            }
            //LoadingPageData 加载分页数据
            PageData<CorporationDto> Data = CorporationService.LoadPageDataList(whereLambda, orderLambda,
                                                                                paramsDto.PageNumber, paramsDto.PageSize,
                                                                                paramsDto.SortOrder.ToLower() == "desc");
            PageData<CorporationDto> pageData = null;
            pageData.Total = Data.Total;
            return pageData;
        }
        [HttpGet]
        public IActionResult Creation(int ID)
        {
            if (ID > 0)
            {
                Task<List<CorporationDto>> CorporationDtos = CorporationService.GetEntityListAsync(s => true).Result
                       .ProjectTo<CorporationDto>(AutoMapper.ConfigurationProvider)
                       .ToListAsync();
            }

            List<SelectListItem> listItems = AreasSelectListItem();
            ViewBag.AreaSelectListItem = listItems;
            return View();
        }
        /// <summary>
        /// 创建公司数据提交
        /// </summary>
        /// <param name="corporationDto">提交公司信息</param>
        /// <returns></returns>
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Creation(CorporationDtoCreation corporationDto)
        {
            JSONData jsondata = new JSONData();
            if (!ModelState.IsValid)
            {
                //ModelState.AddModelError(string.Empty, "自定义描述错误");
                //ModelState.Remove("AreaID");
                //ViewBag.ModelState = ModelState;
                //ViewData["ModelState"] = ModelState;
                //var values = ModelState.Values.Where(s => s.Errors.Any());
                ViewBag.AreaIDs = string.Join(",", corporationDto.AreaID);
                Dictionary<string, string> ModelErrors = new Dictionary<string, string>();

                var keys = ModelState.Keys.Where(k => ModelState[k].Errors.Count > 0);
                foreach (var key in keys)
                {
                    var ErrorMessages = "";
                    if (key == "AreaID")
                    {
                        ErrorMessages = "请正确选择区划地址！";
                    }
                    else
                    {
                        foreach (var error in ModelState[key].Errors)
                        {
                            ErrorMessages += ' ' + error.ErrorMessage;
                        }
                    }
                    ModelErrors.Add(key, ErrorMessages);
                }
                jsondata.Code = EnumCollection.ResponseStatusCode.MODELSTATE;
                jsondata.Data = new { ModelErrors, AreaIDs = string.Join(",", corporationDto.AreaID) };
                jsondata.Message = "数据校验非法，请核实！";
                return Json(jsondata);
            }

            var firstArerID = corporationDto.AreaID.FirstOrDefault();
            if (Constant.SpecialAdministrativeRegionAreaID.Contains(firstArerID))
            {
                if (corporationDto.AreaID.Count < 2)
                {
                    jsondata.Code = EnumCollection.ResponseStatusCode.ARGUMENTSLOSE;
                    jsondata.Message = "请选择完整的区划地址";
                    return Json(jsondata);
                }
            }
            if (corporationDto.AreaID.Count < 4)
            {
                jsondata.Code = EnumCollection.ResponseStatusCode.ARGUMENTSLOSE;
                jsondata.Message = "请选择完整的区划地址";
                return Json(jsondata);
            }

            Corporation corporation = AutoMapper.Map<Corporation>(corporationDto);
            corporation.CreatorUserId = 1000;
            if (CorporationService.IsExisted(corporation))
            {
                jsondata.Code = EnumCollection.ResponseStatusCode.FAIL;
                jsondata.Message = "操作失败：分公司信息已存在，请核实！";
                return Json(jsondata);
            }
            CorporationService.Create(corporation);
            var result = await CorporationService.SaveChangeAsync();
            if (result > 0)
            {
                jsondata.Code = EnumCollection.ResponseStatusCode.SUCCESS;
                jsondata.Message = "操作成功";
                return Json(jsondata);
            }
            return Json(jsondata);
        }

    }
}

LMS.Web/Views/Corporation/CorporationList.cshtml
@{
    ViewBag.Title = "公司列表";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/js/Corporation/CorporationList.js"></script>

LMS.Web/Views/Corporation/Creation.cshtml
@{
    ViewBag.Title = "Corporation Creation";
}
@model CorporationDtoCreation;
<head>
    <link href="~/lib/font-awesome/v4.4.0/css/font-awesome.css" rel="stylesheet" />
</head>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>新增公司</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <form class="form-horizontal m-t" id="FormCorporationCreation" enctype="multipart/form-data" method="post" asp-action="Creation" asp-controller="Corporation">
                            <div class="form-group col-sm-6">
                                <label class="col-sm-3 control-label" asp-for="FullName"></label>
                                <div class="col-sm-9">
                                    <input asp-for="FullName" class="form-control" type="text" placeholder="填写公司全称">
                                    <span asp-validation-for="FullName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group col-sm-6">
                                <label class="col-sm-3 control-label" asp-for="Name"></label>
                                <div class="col-sm-9">
                                    <input asp-for="Name" class="form-control" type="text" placeholder="填写公司简称">
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group col-sm-6">
                                <label class="col-sm-3 control-label" asp-for="BusinessLicense"></label>
                                <div class="col-sm-9">
                                    <input asp-for="BusinessLicense" class="form-control" type="text" placeholder="填写公司营业执照/组织机构代码/税务登记编号">
                                    <span asp-validation-for="BusinessLicense" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group col-sm-6">
                                <label class="col-sm-3 control-label" asp-for="LegalPerson"></label>
                                <div class="col-sm-9">
                                    <input asp-for="LegalPerson" class="form-control" type="text" placeholder="填写公司法人">
                                    <span asp-validation-for="LegalPerson" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group col-sm-6">
                                <label class="col-sm-3 control-label" asp-for="LegalPersonIDCardNo"></label>
                                <div class="col-sm-9">
                                    <input asp-for="LegalPersonIDCardNo" class="form-control" type="text" placeholder="填写公司法人证件号">
                                    <span asp-validation-for="LegalPersonIDCardNo" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group col-sm-6">
                                <label class="col-sm-3 control-label" asp-for="LegalPersonPhone"></label>
                                <div class="col-sm-9">
                                    <input asp-for="LegalPersonPhone" class="form-control" type="text" placeholder="填写公司法人手机号">
                                    <span asp-validation-for="LegalPersonPhone" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group col-sm-6">
                                <label class="col-sm-3 control-label" asp-for="Telephone"></label>
                                <div class="col-sm-9">
                                    <input asp-for="Telephone" class="form-control" type="text" placeholder="填写公司联系电话">
                                    <span asp-validation-for="Telephone" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group col-sm-6">
                                <label class="col-sm-3 control-label" asp-for="FaxNumber"></label>
                                <div class="col-sm-9">
                                    <input asp-for="FaxNumber" class="form-control" type="text" placeholder="填写公司传真号">
                                    <span asp-validation-for="FaxNumber" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group col-sm-6">
                                <label class="col-sm-3 control-label" asp-for="SupportEMail"></label>
                                <div class="col-sm-9">
                                    <input asp-for="SupportEMail" class="form-control" type="text" placeholder="填写公司服务支持邮件地址">
                                    <span asp-validation-for="SupportEMail" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group col-sm-6">
                                <label class="col-sm-3 control-label" asp-for="AreaID"></label>
                                <div class="col-sm-9">
                                    <select class="form-control col-sm-4 selectpicker show-tick" data-live-search="true" data-style="btn-success" data-size="11" data-width="fit" data-actions-box="true" title="请选择" name="AreaID" id="seltProvinceAreaID">
                                    </select>
                                    <select class="form-control col-sm-4 selectpicker show-tick" data-live-search="true" data-style="btn-success" data-size="11" data-width="fit" data-actions-box="true" title="请选择" name="AreaID" id="seltCityAreaID">
                                    </select>
                                    <select class="form-control col-sm-4 selectpicker show-tick" data-live-search="true" data-style="btn-success" data-size="11" data-width="fit" data-actions-box="true" title="请选择" name="AreaID" id="seltCistrictAreaID">
                                    </select>
                                    <select class="form-control col-sm-4 selectpicker show-tick" data-live-search="true" data-style="btn-success" data-size="11" data-width="auto" data-actions-box="true" title="请选择" name="AreaID" id="seltStreetAreaID">
                                    </select>
                                    <span asp-validation-for="AreaID" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group col-sm-6">
                                <label class="col-sm-3 control-label" asp-for="CorporationAddress"></label>
                                <div class="col-sm-9">
                                    <input asp-for="CorporationAddress" id="CorporationAddress" class="form-control" type="text" placeholder="请填写公司所在区划之后的详细地址">
                                    <span asp-validation-for="CorporationAddress" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group col-sm-6">
                                <label class="col-sm-3 control-label">上传图片</label>
                                <div id="wrapper">
                                    <div id="container">
                                        <!--头部，相册选择和格式选择-->
                                        <div id="uploader">
                                            <div class="queueList">
                                                <div id="dndArea" class="placeholder">
                                                    <div id="filePicker"></div>
                                                    <p>或将照片拖到这里，单次最多可选300张</p>
                                                </div>
                                            </div>
                                            <div class="statusBar" style="display:none;">
                                                <div class="progress">
                                                    <span class="text">0%</span>
                                                    <span class="percentage"></span>
                                                </div><div class="info"></div>
                                                <div class="btns">
                                                    <div id="filePicker2"></div><div class="uploadBtn">开始上传</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group  col-sm-12">
                                <div class="col-sm-9 col-sm-offset-1">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" class="checkbox" id="agree" name="agree"> 我已经认真阅读并同意《使用协议》
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group  col-sm-6 hidden" id="divModelErrors"></div>


                            <div class="form-group ">
                                <div class="col-sm-9 col-sm-offset-1">
                                    <button class="btn btn-primary" id="btnSubmit" type="button">提交</button>
                                    <button class="btn btn-default" type="button">取消</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>

    @section Scripts {
        <!-- 自定义js -->
        <script src="~/js/public/content.js?v=1.0"></script>
        @{await Html.RenderPartialAsync("_BootstrapSelectPartial"); }
        @{await Html.RenderPartialAsync("_BootstrapValidatorPartial"); }
        @{await Html.RenderPartialAsync("_AjaxFromPartial"); }
        @{await Html.RenderPartialAsync("_WebUploadPartial"); }

        <script src="~/js/Corporation/Creation.js"></script>
    }
</body>